language: python

python:
        - "2.7"
virtualenv:
      system_site_packages: true

install:
        - sudo apt-get install expect
        - sudo apt-get install python-qt4
        - sudo apt-get install qgis
        - sudo apt-get install python-qgis
        - sudo apt-get install vnc4server # to mock an X Server
        - pip install mock
        - pip install nose
        - pip install coverage

before_script:
        - expect vnc.expect 1001 # handle the interactive setup of vnc
    # - export DISPLAY=localhost:1001
script:  export DISPLAY=localhost:1001;sh run_tests.sh


